packages:
  - ./
  - playground
  - docs

linkWorkspacePackages: true

allowBuilds:
  sharp: true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  better-sqlite3: false
