blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://strapi.nuxtjs.org
    about: Check the documentation for guides and examples.
  - name: 💬 Questions & Help
    url: https://discord.nuxtjs.org/
    about: Ask questions about the module on the Nuxt Community Discord.
